config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rucio/rucio:
      branch: master
      repo: https://github.com/rucio/rucio
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rucio/rucio git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-cardinal-tortoise.sh
        container: qc.acc_woozy-lilac-cougar
  QC.Doc:
    repos:
      github.com/rucio/rucio find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-charcoal-bullfrog.sh
        container: qc.doc_shabby-mauve-discus
      github.com/rucio/rucio git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-olivine-squirrel.sh
        container: qc.doc_clammy-buff-tarsier
      github.com/rucio/rucio markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-amber-giraffe.sh
        container: qc.doc_leaky-heliotrope-dhole
      github.com/rucio/rucio restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-tangerine-goat.sh
        container: qc.doc_nerdy-platinum-chinchilla
  QC.Lic:
    repos:
      github.com/rucio/rucio licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-smalt-stingray.sh
        container: qc.lic_woozy-champagne-camel
  QC.Sec:
    repos:
      github.com/rucio/rucio bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-bronze-capuchin.sh
        container: qc.sec_messy-alizarin-gibbon
  QC.Sty:
    repos:
      github.com/rucio/rucio flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-teal-akbash.sh
        container: qc.sty_wimpy-khaki-emu
      github.com/rucio/rucio jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-bistre-ostrich.sh
        container: qc.sty_sunny-puce-cassowary
  QC.Uni:
    repos:
      github.com/rucio/rucio pytest:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-gold-bat.sh
        container: qc.uni_fuzzy-xanthic-uakari
  QC.Ver:
    repos:
      github.com/rucio/rucio get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-silver-mammoth.sh
        container: qc.ver_droopy-coral-coyote
timeout: 5400
