config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rucio/rucio:
      branch: master
      repo: https://github.com/rucio/rucio
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rucio/rucio git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-pear-monster.sh
        container: qc.acc_squeaky-scarlet-buffalo
  QC.Doc:
    repos:
      github.com/rucio/rucio find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-amethyst-paradise.sh
        container: qc.doc_blurry-cerise-zebra
      github.com/rucio/rucio git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-gold-dane.sh
        container: qc.doc_fuzzy-amethyst-ferret
      github.com/rucio/rucio markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-firebrick-olm.sh
        container: qc.doc_sloppy-lavender-hamster
      github.com/rucio/rucio restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-heliotrope-walrus.sh
        container: qc.doc_skinny-lime-earwig
  QC.Lic:
    repos:
      github.com/rucio/rucio licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-wisteria-bat.sh
        container: qc.lic_homely-lime-barracuda
  QC.Sec:
    repos:
      github.com/rucio/rucio bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-sangria-tetra.sh
        container: qc.sec_shabby-peach-ragdoll
  QC.Sty:
    repos:
      github.com/rucio/rucio flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-green-hyrax.sh
        container: qc.sty_smelly-ochre-indri
      github.com/rucio/rucio jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-eggplant-hedgehog.sh
        container: qc.sty_slimy-charcoal-barracuda
  QC.Uni:
    repos:
      github.com/rucio/rucio pytest:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-brown-wallaby.sh
        container: qc.uni_paltry-tangerine-jellyfish
  QC.Ver:
    repos:
      github.com/rucio/rucio get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cerulean-bloodhound.sh
        container: qc.ver_pasty-zucchini-markhor
timeout: 5400
